-- ============================================================
-- NYC Taxi Analytics Platform — dbt Role & Service User
-- ============================================================
-- Creates NYC_TAXI_DBT_ROLE (scoped grants for dbt transformations)
-- and NYC_TAXI_DBT_SVC_USER (the dedicated service identity dbt
-- authenticates as — separate from personal/admin logins, same
-- least-privilege separation used for the AWS ingestion user).
--
-- Run with:
--   snowsql -c <your_connection_profile> -f snowflake/02_dbt_role_and_user.sql -o exit_on_error=true
-- ============================================================

CREATE ROLE IF NOT EXISTS NYC_TAXI_DBT_ROLE;

GRANT USAGE ON WAREHOUSE NYC_TAXI_WH TO ROLE NYC_TAXI_DBT_ROLE;
GRANT USAGE ON DATABASE NYC_TAXI_ANALYTICS TO ROLE NYC_TAXI_DBT_ROLE;

-- RAW: read-only. dbt sources from here, never writes here.
GRANT USAGE ON SCHEMA NYC_TAXI_ANALYTICS.RAW TO ROLE NYC_TAXI_DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NYC_TAXI_ANALYTICS.RAW TO ROLE NYC_TAXI_DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NYC_TAXI_ANALYTICS.RAW TO ROLE NYC_TAXI_DBT_ROLE;

-- STAGING: dbt owns this fully
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI_ANALYTICS.STAGING TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA NYC_TAXI_ANALYTICS.STAGING TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA NYC_TAXI_ANALYTICS.STAGING TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.STAGING TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.STAGING TO ROLE NYC_TAXI_DBT_ROLE;

-- INTERMEDIATE: same pattern
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI_ANALYTICS.INTERMEDIATE TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA NYC_TAXI_ANALYTICS.INTERMEDIATE TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA NYC_TAXI_ANALYTICS.INTERMEDIATE TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.INTERMEDIATE TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.INTERMEDIATE TO ROLE NYC_TAXI_DBT_ROLE;

-- MARTS: same pattern
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI_ANALYTICS.MARTS TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA NYC_TAXI_ANALYTICS.MARTS TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA NYC_TAXI_ANALYTICS.MARTS TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.MARTS TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.MARTS TO ROLE NYC_TAXI_DBT_ROLE;

-- Assign the role to yourself:
GRANT ROLE NYC_TAXI_DBT_ROLE TO USER DSDENISOV;

CREATE USER IF NOT EXISTS NYC_TAXI_DBT_SVC_USER
  -- Replace with the actual RSA public key content (no BEGIN/END headers,
  -- no line breaks). Generated locally, never committed — see
  -- docs/design_decisions.md for the key-pair setup used for this project.
  RSA_PUBLIC_KEY = '<your_public_key_here>'
  DEFAULT_ROLE = NYC_TAXI_DBT_ROLE
  DEFAULT_WAREHOUSE = NYC_TAXI_WH
  DEFAULT_NAMESPACE = NYC_TAXI_ANALYTICS.STAGING
  COMMENT = 'Service account for dbt runs. Automation only, no interactive login expected.';
GRANT ROLE NYC_TAXI_DBT_ROLE TO USER NYC_TAXI_DBT_SVC_USER;