-- ============================================================
-- NYC Taxi Analytics Platform — Snowflake Role & Access Control
-- ============================================================
-- Creates NYC_TAXI_DBT_ROLE, used by dbt (and later Airflow) to
-- run transformations. Deliberately scoped:
--   - SELECT-only on RAW (dbt sources from raw, never writes to it)
--   - full CREATE/DROP on STAGING, INTERMEDIATE, MARTS
--   - no CREATE WAREHOUSE / CREATE DATABASE / CREATE ROLE
--
-- Run with:
--   snowsql -c <your_connection_profile> -f snowflake/02_roles.sql -o exit_on_error=true
-- ============================================================

CREATE ROLE IF NOT EXISTS NYC_TAXI_DBT_ROLE;

GRANT USAGE ON WAREHOUSE NYC_TAXI_WH TO ROLE NYC_TAXI_DBT_ROLE;
GRANT USAGE ON DATABASE NYC_TAXI_ANALYTICS TO ROLE NYC_TAXI_DBT_ROLE;

-- RAW: read-only. dbt sources from here, never writes here.
GRANT USAGE ON SCHEMA NYC_TAXI_ANALYTICS.RAW TO ROLE NYC_TAXI_DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NYC_TAXI_ANALYTICS.RAW TO ROLE NYC_TAXI_DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NYC_TAXI_ANALYTICS.RAW TO ROLE NYC_TAXI_DBT_ROLE;

-- STAGING: dbt owns this fully
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI_ANALYTICS.STAGING TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA NYC_TAXI_ANALYTICS.STAGING TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA NYC_TAXI_ANALYTICS.STAGING TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.STAGING TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.STAGING TO ROLE NYC_TAXI_DBT_ROLE;

-- INTERMEDIATE: same pattern
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI_ANALYTICS.INTERMEDIATE TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA NYC_TAXI_ANALYTICS.INTERMEDIATE TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA NYC_TAXI_ANALYTICS.INTERMEDIATE TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.INTERMEDIATE TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.INTERMEDIATE TO ROLE NYC_TAXI_DBT_ROLE;

-- MARTS: same pattern
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI_ANALYTICS.MARTS TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA NYC_TAXI_ANALYTICS.MARTS TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA NYC_TAXI_ANALYTICS.MARTS TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.MARTS TO ROLE NYC_TAXI_DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA NYC_TAXI_ANALYTICS.MARTS TO ROLE NYC_TAXI_DBT_ROLE;

-- Assign the role to yourself:
GRANT ROLE NYC_TAXI_DBT_ROLE TO USER DSDENISOV;